### ISSUE TITLE
Dialog bug

### ISSUE THREAD

**Issue by l1068** [AperoVN/AperoModuleAds#20]
Hi, while onBackpress, if I click the exit or close buttons instead of closing the dialog, it's closing the app.

https://github.com/AperoVN/AperoModuleAds/blob/develop/app/src/main/java/com/example/andmoduleads/activity/MainActivity.java#L217

**Comment by lamlt95** [comment]
It's just sample. you can remove `MainActivity.super.onBackPressed()` in callback onExit
