### ISSUE TITLE
Disable AdsResume when back from request permission.

### ISSUE THREAD

**Issue by dbackspace** [AperoVN/AperoModuleAds#25]
Hello,
When I request any permission (e.g Usage data access,...) and back to Main Activity, the AdsResume is showing. How can I disable it if user only case back from request permission screen, and still showing when back from other app?
Thank you.

**Comment by lamlt95** [comment]
Call this when request permission. it disable AdsResume when back to screen
`AppOpenManager.getInstance().disableAdResumeByClickAction();`

**Comment by dbackspace** [comment]
Thanks for your help :D
