### ISSUE TITLE
IAP and Subscription shown incorrect

### ISSUE THREAD

**Issue by dbackspace** [AperoVN/AperoModuleAds#28]
Hello developer team,
When I request subscribe or purchase by AppPurchase.getInstance().purchase(requireActivity(), PURCHASE_KEY, the purchasing/subscription dialog is showing incorrect. So I can't test the operation. Description details is in image attached. Please help me to check it. Thanks. 
![Screenshot_20221109_165304_Google Play Store](https://user-images.githubusercontent.com/42472693/200798865-73a95ff3-76d1-4d94-b77a-8ec146fc9a80.jpg)

**Comment by lamlt95** [comment]
This seems to be an issue from the google SDK. that we have not been able to fix. you can try on another device, or use this guide
https://developer.android.com/google/play/billing/test
