### ISSUE TITLE
how to disable loading ad  in native?

### ISSUE THREAD

**Issue by aZyreTech** [AperoVN/AperoModuleAds#35]
I have native ad in one of my activity. If network gets disconnected/reconnected native ad not showing instead of that it only shows loading ad. How to reload native ad after reconnect ?

**Comment by lamlt95** [comment]
This moment, you can use load native ad with `loadNativeAdResultCallback` and INVISIBLE  loading when load fail, or check state internet. Native ad cant auto reload after reconnect.
